/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal.difusaocalor;

// import javax.swing.border.LineBorder; (não usado após remoção das bordas das células)
import java.awt.BorderLayout;
// import java.awt.Color; (não usado aqui)
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaneko
 */
public class FormPrincipal extends javax.swing.JFrame {

    private static final int MAX_RECORDED_FRAMES = 300;
    private static final int MAX_DISPLAY_SIZE = 200;

    private HeatGridPanel heatPanel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel lblStatus;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        // configura listeners adicionais que não são gerados pelo NetBeans
        setupListeners();
    }

    private void setupListeners() {
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }
        };
        txtAltura.getDocument().addDocumentListener(docListener);
        txtCoeficienteMaterial.getDocument().addDocumentListener(docListener);
        txtTempo.getDocument().addDocumentListener(docListener);
        // listener para campo de URLs dos workers (modo distribuído)
        txtWorkerUrls.getDocument().addDocumentListener(docListener);

        // checkboxes already have action listeners generated -> reuse them to update
        // state
        // ensure initial state is correct
        updateEnviarEnabled();
    }

    private void updateEnviarEnabled() {
        boolean modeSelected = rbSequencial.isSelected() || rbParalelo.isSelected() || rbDistribuido.isSelected();
        boolean inputsFilled = !txtAltura.getText().trim().isEmpty()
                && !txtCoeficienteMaterial.getText().trim().isEmpty()
                && !txtTempo.getText().trim().isEmpty();
        // se modo distribuído selecionado, requerer URLs
        if (rbDistribuido.isSelected()) {
            inputsFilled = inputsFilled && txtWorkerUrls != null && !txtWorkerUrls.getText().trim().isEmpty();
        }
        boolean positionSelected = cbCima.isSelected() || cbBaixo.isSelected() || cbDireita.isSelected()
                || cbEsquerda.isSelected();
        btnEnviar.setEnabled(modeSelected && inputsFilled && positionSelected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDimensao = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        cbCima = new javax.swing.JCheckBox();
        cbBaixo = new javax.swing.JCheckBox();
        cbEsquerda = new javax.swing.JCheckBox();
        cbDireita = new javax.swing.JCheckBox();
        lblPosicaoCalor = new javax.swing.JLabel();
        lblCoeficienteMaterial = new javax.swing.JLabel();
        txtCoeficienteMaterial = new javax.swing.JTextField();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        btnLimpar = new javax.swing.JToggleButton();
        pnMalha = new javax.swing.JPanel();
        rbParalelo = new javax.swing.JRadioButton();
        rbSequencial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDimensao.setText("Dimensão da Malha (X * Y)");

        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        cbCima.setText("Cima");
        cbCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCimaActionPerformed(evt);
            }
        });

        cbBaixo.setText("Baixo");
        cbBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaixoActionPerformed(evt);
            }
        });

        cbEsquerda.setText("Esquerda");
        cbEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsquerdaActionPerformed(evt);
            }
        });

        cbDireita.setText("Direita");
        cbDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDireitaActionPerformed(evt);
            }
        });

        lblPosicaoCalor.setText("Posição do calor");

        lblCoeficienteMaterial.setText("Coeficiente do Material ");

        txtCoeficienteMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoeficienteMaterialActionPerformed(evt);
            }
        });

        lblTempo.setText("Tempo (s)");

        txtTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        // inicialmente desabilitado até que um modo seja escolhido
        btnEnviar.setEnabled(false);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnResultados.setText("Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        // remover borda externa para que a malha comece na borda do painel
        pnMalha.setBorder(null);
        pnMalha.setToolTipText("");
        pnMalha.setName(""); // NOI18N
        pnMalha.setPreferredSize(new java.awt.Dimension(500, 500));
        // usamos BorderLayout como container para o painel customizado de desenho
        pnMalha.setLayout(new BorderLayout());

        // status (barra de progresso) será adicionado ao sul de pnMalha quando a malha
        // for criada

        // ordem desejada: Sequencial, Paralelo, Distribuído
        buttonGroup1.add(rbSequencial);
        rbSequencial.setText("Sequencial");
        rbSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSequencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbParalelo);
        rbParalelo.setText("Paralelo");
        rbParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParaleloActionPerformed(evt);
            }
        });

        // novo radio button para modo distribuído (ainda sem funcionalidade)
        rbDistribuido = new javax.swing.JRadioButton();
        buttonGroup1.add(rbDistribuido);
        rbDistribuido.setText("Distribuído");
        rbDistribuido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDistribuidoActionPerformed(evt);
            }
        });

        // campo para informar URLs dos workers RMI (separo por vírgula)
        lblWorkerUrls = new javax.swing.JLabel();
        txtWorkerUrls = new javax.swing.JTextField();
        lblWorkerUrls.setText("Workers RMI (vírgula separado)");
        txtWorkerUrls.setText("rmi://localhost:1099/Worker1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(txtAltura,
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lblDimensao,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(cbCima, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbDireita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbBaixo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbEsquerda,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbSequencial,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbParalelo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbDistribuido,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblWorkerUrls)
                                                        .addComponent(txtWorkerUrls,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(83, 83, 83)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(lblCoeficienteMaterial,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txtCoeficienteMaterial)
                                                                .addComponent(txtTempo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblTempo))
                                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnResultados,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblPosicaoCalor))
                                .addGap(58, 58, 58)
                                .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblCoeficienteMaterial)
                                                        .addComponent(lblDimensao))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtCoeficienteMaterial,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblTempo)
                                                        .addComponent(rbSequencial))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbParalelo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbDistribuido)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblWorkerUrls)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtWorkerUrls, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblPosicaoCalor)
                                                .addGap(21, 21, 21)
                                                .addComponent(cbCima)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbBaixo)
                                                        .addComponent(btnEnviar))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbDireita)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbEsquerda))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(btnLimpar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnResultados,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(16, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCimaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbCimaActionPerformed
        // estado do checkbox lido quando necessário pela simulação
        updateEnviarEnabled();
    }// GEN-LAST:event_cbCimaActionPerformed

    private void cbBaixoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbBaixoActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbBaixoActionPerformed

    private void cbEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbEsquerdaActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbEsquerdaActionPerformed

    private void cbDireitaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbDireitaActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbDireitaActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAlturaActionPerformed

    }// GEN-LAST:event_txtAlturaActionPerformed

    private void txtTempoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTempoActionPerformed
        try {
            Integer.parseInt(txtTempo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor inválido para tempo. Digite um inteiro.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_txtTempoActionPerformed

    private void txtCoeficienteMaterialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCoeficienteMaterialActionPerformed
        try {
            Double.parseDouble(txtCoeficienteMaterial.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor inválido para coeficiente. Digite um número.",
                    "Entrada inválida", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_txtCoeficienteMaterialActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }// GEN-LAST:event_btnLimparActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResultadosActionPerformed
        // lê parâmetros da UI
        int n;
        double alpha;
        int steps;
        int repeats = 3; // padrão
        try {
            n = Integer.parseInt(txtAltura.getText());
            alpha = Double.parseDouble(txtCoeficienteMaterial.getText());
            steps = Integer.parseInt(txtTempo.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique as entradas: dimensão, coeficiente e tempo devem ser números.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        final int fn = n;
        final double falpha = alpha;
        final int fsteps = steps;
        final int frepeats = repeats;

        // pega URLs (opcional)
        final java.util.List<String> urls = new java.util.ArrayList<>();
        String urlsText = txtWorkerUrls.getText().trim();
        if (!urlsText.isEmpty()) {
            for (String p : urlsText.split(",")) {
                String u = p.trim();
                if (!u.isEmpty())
                    urls.add(u);
            }
        }

        // executa em background para não travar a UI
        btnResultados.setEnabled(false);
        btnEnviar.setEnabled(false);
        btnLimpar.setEnabled(false);

        javax.swing.SwingWorker<Void, Void> worker = new javax.swing.SwingWorker<>() {
            private BenchmarkUtil.Stats seqStats;
            private BenchmarkUtil.Stats distStats;

            @Override
            protected Void doInBackground() throws Exception {
                seqStats = BenchmarkUtil.runSequential(fn, falpha, fsteps, frepeats);
                if (!urls.isEmpty()) {
                    distStats = BenchmarkUtil.runDistributed(fn, falpha, fsteps, frepeats, urls);
                }
                return null;
            }

            @Override
            protected void done() {
                btnResultados.setEnabled(true);
                btnEnviar.setEnabled(true);
                btnLimpar.setEnabled(true);

                String header = String.format("Benchmark (n=%d steps=%d repeats=%d)", fn, fsteps, frepeats);

                // cria diálogo com texto e gráfico
                javax.swing.JDialog dlg = new javax.swing.JDialog(FormPrincipal.this, "Resultados do Benchmark", true);
                dlg.setLayout(new java.awt.BorderLayout());

                StringBuilder sb = new StringBuilder();
                if (seqStats != null && !seqStats.runs.isEmpty()) {
                    sb.append(String.format("Sequencial — mean=%.6fs median=%.6fs sd=%.6fs\n", seqStats.mean,
                            seqStats.median, seqStats.sd));
                } else {
                    sb.append("Sequencial — sem dados\n");
                }
                if (distStats != null && !distStats.runs.isEmpty()) {
                    sb.append(String.format("Distribuído — mean=%.6fs median=%.6fs sd=%.6fs\n", distStats.mean,
                            distStats.median, distStats.sd));
                    if (seqStats != null && !Double.isNaN(seqStats.mean)) {
                        double ratio = seqStats.mean / distStats.mean;
                        if (ratio > 1.0) {
                            sb.append(String.format("Resultado: Distribuído foi mais rápido (speedup=%.2f×)\n", ratio));
                        } else if (ratio < 1.0) {
                            sb.append(String.format("Resultado: Sequencial foi mais rápido (speedup=%.2f×)\n",
                                    1.0 / ratio));
                        } else {
                            sb.append("Resultado: Empate (tempos iguais)\n");
                        }
                    }
                } else {
                    sb.append("Distribuído — sem dados (nenhum worker configurado ou falha)\n");
                }

                javax.swing.JTextArea ta = new javax.swing.JTextArea(header + "\n\n" + sb.toString());
                ta.setEditable(false);
                ta.setBackground(dlg.getBackground());
                ta.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
                dlg.add(ta, java.awt.BorderLayout.NORTH);

                BenchmarkChartPanel chart = new BenchmarkChartPanel(seqStats == null ? null : seqStats.runs,
                        distStats == null ? null : distStats.runs);
                chart.setPreferredSize(new java.awt.Dimension(600, 300));
                dlg.add(chart, java.awt.BorderLayout.CENTER);

                javax.swing.JButton close = new javax.swing.JButton("Fechar");
                close.addActionListener(ae -> dlg.dispose());
                javax.swing.JPanel bottom = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
                bottom.add(close);
                dlg.add(bottom, java.awt.BorderLayout.SOUTH);

                dlg.pack();
                dlg.setLocationRelativeTo(FormPrincipal.this);
                dlg.setVisible(true);
            }
        };

        worker.execute();
    }// GEN-LAST:event_btnResultadosActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
        gerarMalha();
        simularDifusao();
    }// GEN-LAST:event_btnEnviarActionPerformed

    private void rbParaleloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbParaleloActionPerformed
        // seleção alterada — atualiza estado do botão Enviar
        updateEnviarEnabled();
    }// GEN-LAST:event_rbParaleloActionPerformed

    private void rbSequencialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbSequencialActionPerformed
        // seleção alterada — atualiza estado do botão Enviar
        updateEnviarEnabled();
    }// GEN-LAST:event_rbSequencialActionPerformed

    private void rbDistribuidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbDistribuidoActionPerformed
        // distribuído selecionado - funcionalidade não implementada ainda
        updateEnviarEnabled();
    }// GEN-LAST:event_rbDistribuidoActionPerformed

    private void limpar() {
        txtAltura.setText("");
        txtCoeficienteMaterial.setText("");
        txtTempo.setText("");
        pnMalha.removeAll();
        pnMalha.revalidate();
        pnMalha.repaint();
        cbCima.setSelected(false);
        cbBaixo.setSelected(false);
        cbDireita.setSelected(false);
        cbEsquerda.setSelected(false);
        buttonGroup1.clearSelection();
        // desabilita Enviar até nova seleção e atualiza estado
        updateEnviarEnabled();
    }

    private void gerarMalha() {
        int altura = 1;
        try {
            altura = Integer.parseInt(txtAltura.getText());
            if (altura <= 0)
                throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dimensão inválida. Digite um inteiro positivo.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        pnMalha.removeAll();

        // cria um painel customizado que desenha toda a malha em uma só superfície
        heatPanel = new HeatGridPanel(altura);
        pnMalha.add(heatPanel, BorderLayout.CENTER);

        // cria painel de status (barra de progresso + label) e adiciona ao sul da área
        // da malha
        progressBar = new javax.swing.JProgressBar(0, 100);
        progressBar.setValue(0);
        progressBar.setStringPainted(true);
        lblStatus = new javax.swing.JLabel("Pronto");
        javax.swing.JPanel statusPanel = new javax.swing.JPanel(new BorderLayout());
        statusPanel.add(progressBar, BorderLayout.CENTER);
        statusPanel.add(lblStatus, BorderLayout.EAST);
        pnMalha.add(statusPanel, BorderLayout.SOUTH);

        pnMalha.revalidate();
        pnMalha.repaint();
    }

    // ---------------- DIFUSÃO DE CALOR ----------------
    private void simularDifusao() {
        int n;
        double alpha;
        int tempoIteracoes;

        try {
            n = Integer.parseInt(txtAltura.getText());
            alpha = Double.parseDouble(txtCoeficienteMaterial.getText());
            tempoIteracoes = Integer.parseInt(txtTempo.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique as entradas: dimensão, coeficiente e tempo devem ser números.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        ExecutionMode mode;
        if (rbSequencial.isSelected()) {
            mode = ExecutionMode.SEQUENCIAL;
        } else if (rbParalelo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Modo paralelo não implementado. Executando em modo sequencial.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            mode = ExecutionMode.SEQUENCIAL;
        } else if (rbDistribuido.isSelected()) {
            mode = ExecutionMode.DISTRIBUIDO;
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um modo de execução (Sequencial/Paralelo/Distribuído).",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<String> workerUrls = new ArrayList<>();
        if (mode == ExecutionMode.DISTRIBUIDO) {
            String urlsText = txtWorkerUrls.getText().trim();
            if (urlsText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe ao menos um URL de worker para o modo distribuído.",
                        "Entrada inválida", JOptionPane.ERROR_MESSAGE);
                return;
            }
            for (String raw : urlsText.split(",")) {
                String cleaned = raw.trim();
                if (!cleaned.isEmpty())
                    workerUrls.add(cleaned);
            }
            if (workerUrls.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe ao menos um URL de worker válido.", "Entrada inválida",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        final boolean cima = cbCima.isSelected();
        final boolean baixo = cbBaixo.isSelected();
        final boolean esquerda = cbEsquerda.isSelected();
        final boolean direita = cbDireita.isSelected();

        runMeasuredSimulation(mode, n, alpha, tempoIteracoes, workerUrls, cima, baixo, esquerda, direita);
    }

    private enum ExecutionMode {
        SEQUENCIAL,
        PARALELO,
        DISTRIBUIDO
    }

    private static class SimulationFrame {
        final int step;
        final double[][] snapshot;

        SimulationFrame(int step, double[][] snapshot) {
            this.step = step;
            this.snapshot = snapshot;
        }
    }

    private static class SimulationPlaybackData {
        final double elapsedSeconds;
        final List<SimulationFrame> frames;
        final int totalSteps;
        final double[][] finalStateFull;

        SimulationPlaybackData(double elapsedSeconds, List<SimulationFrame> frames, int totalSteps,
                double[][] finalStateFull) {
            this.elapsedSeconds = elapsedSeconds;
            this.frames = Collections.unmodifiableList(new ArrayList<>(frames));
            this.totalSteps = totalSteps;
            this.finalStateFull = finalStateFull;
        }
    }

    private AbstractHeatSimulator buildSimulator(ExecutionMode mode, int n, double alpha, List<String> workerUrls) {
        switch (mode) {
            case DISTRIBUIDO:
                return new DistributedHeatSimulator(n, alpha, workerUrls);
            case PARALELO:
            case SEQUENCIAL:
            default:
                return new SequentialHeatSimulator(n, alpha);
        }
    }

    private void cleanupSimulator(AbstractHeatSimulator simulator) {
        if (simulator instanceof DistributedHeatSimulator) {
            try {
                ((DistributedHeatSimulator) simulator).shutdown();
            } catch (Exception ignore) {
            }
        }
    }

    private void runMeasuredSimulation(ExecutionMode mode, int n, double alpha, int totalSteps,
            List<String> workerUrls, boolean cima, boolean baixo, boolean esquerda, boolean direita) {
        final ExecutionMode chosenMode = mode;
        final List<String> urlsCopy = new ArrayList<>(workerUrls);

        if (progressBar != null) {
            progressBar.setIndeterminate(true);
            progressBar.setValue(0);
        }
        if (lblStatus != null) {
            lblStatus.setText("Calculando simulação real...");
        }
        btnEnviar.setEnabled(false);
        btnLimpar.setEnabled(false);

        javax.swing.SwingWorker<SimulationPlaybackData, Void> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected SimulationPlaybackData doInBackground() throws Exception {
                AbstractHeatSimulator sim = buildSimulator(chosenMode, n, alpha, urlsCopy);
                sim.setBoundaryFlags(cima, baixo, esquerda, direita);

                List<SimulationFrame> frames = new ArrayList<>();
                frames.add(new SimulationFrame(0, downsampleMatrix(sim.getTemperatureCopy())));

                int stride = Math.max(1, (int) Math.ceil((double) totalSteps / MAX_RECORDED_FRAMES));
                long start = System.nanoTime();
                double[][] finalState = null;

                for (int step = 1; step <= totalSteps; step++) {
                    sim.step();
                    if (step % stride == 0 || step == totalSteps) {
                        double[][] snapshot = sim.getTemperatureCopy();
                        if (step == totalSteps) {
                            finalState = snapshot;
                        }
                        frames.add(new SimulationFrame(step, downsampleMatrix(snapshot)));
                    }
                }

                long end = System.nanoTime();
                double elapsed = (end - start) / 1_000_000_000.0;
                cleanupSimulator(sim);
                return new SimulationPlaybackData(elapsed, frames, totalSteps, finalState);
            }

            @Override
            protected void done() {
                if (progressBar != null) {
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(0);
                }
                SimulationPlaybackData data;
                try {
                    data = get();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(FormPrincipal.this,
                            "Falha ao executar a simulação: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    finalizePlaybackFailure();
                    return;
                }
                playbackSimulation(data);
            }
        };

        worker.execute();
    }

    private void playbackSimulation(SimulationPlaybackData data) {
        if (heatPanel == null || data.frames.isEmpty()) {
            finalizePlaybackSuccess(data);
            return;
        }

        if (progressBar != null) {
            progressBar.setValue(0);
        }
        if (lblStatus != null) {
            lblStatus.setText(String.format("Reproduzindo simulação — tempo real %.3fs", data.elapsedSeconds));
        }

        final int[] index = { 0 };
        javax.swing.Timer timer = new javax.swing.Timer(50, null);
        timer.addActionListener(e -> {
            if (index[0] >= data.frames.size()) {
                ((javax.swing.Timer) e.getSource()).stop();
                finalizePlaybackSuccess(data);
                return;
            }
            SimulationFrame frame = data.frames.get(index[0]);
            heatPanel.setTemperature(frame.snapshot);
            updatePlaybackStatus(frame.step, data.totalSteps, data.elapsedSeconds);
            index[0]++;
        });
        timer.start();
    }

    private void updatePlaybackStatus(int step, int totalSteps, double elapsedSeconds) {
        int pct = totalSteps == 0 ? 100 : Math.min(100, (int) ((step * 100L) / totalSteps));
        if (progressBar != null) {
            progressBar.setValue(pct);
        }
        if (lblStatus != null) {
            lblStatus.setText(String.format("It: %d/%d — tempo real %.3fs", step, totalSteps, elapsedSeconds));
        }
        this.setTitle(String.format("Difusão de Calor — %d%%", pct));
    }

    private void finalizePlaybackSuccess(SimulationPlaybackData data) {
        if (heatPanel != null && data.finalStateFull != null) {
            heatPanel.setTemperature(downsampleMatrix(data.finalStateFull));
        }
        if (progressBar != null) {
            progressBar.setValue(100);
            progressBar.setIndeterminate(false);
        }
        if (lblStatus != null) {
            lblStatus.setText(String.format("Concluído — tempo real: %.3fs", data.elapsedSeconds));
        }
        btnEnviar.setEnabled(true);
        btnLimpar.setEnabled(true);
        this.setTitle("Difusão de Calor");
    }

    private void finalizePlaybackFailure() {
        if (progressBar != null) {
            progressBar.setValue(0);
            progressBar.setIndeterminate(false);
        }
        if (lblStatus != null) {
            lblStatus.setText("Simulação não iniciada");
        }
        btnEnviar.setEnabled(true);
        btnLimpar.setEnabled(true);
        this.setTitle("Difusão de Calor");
    }

    private double[][] downsampleMatrix(double[][] source) {
        if (source == null) {
            return null;
        }
        int n = source.length;
        if (n == 0) {
            return new double[0][0];
        }
        if (n <= MAX_DISPLAY_SIZE) {
            double[][] copy = new double[n][n];
            for (int i = 0; i < n; i++) {
                System.arraycopy(source[i], 0, copy[i], 0, n);
            }
            return copy;
        }

        int factor = (int) Math.ceil((double) n / MAX_DISPLAY_SIZE);
        int target = (int) Math.ceil((double) n / factor);
        double[][] result = new double[target][target];
        for (int i = 0; i < target; i++) {
            for (int j = 0; j < target; j++) {
                double sum = 0.0;
                int count = 0;
                int startI = i * factor;
                int startJ = j * factor;
                for (int si = startI; si < Math.min(n, startI + factor); si++) {
                    for (int sj = startJ; sj < Math.min(n, startJ + factor); sj++) {
                        sum += source[si][sj];
                        count++;
                    }
                }
                result[i][j] = count == 0 ? 0.0 : sum / count;
            }
        }
        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBaixo;
    private javax.swing.JCheckBox cbCima;
    private javax.swing.JCheckBox cbDireita;
    private javax.swing.JCheckBox cbEsquerda;
    private javax.swing.JLabel lblCoeficienteMaterial;
    private javax.swing.JLabel lblDimensao;
    private javax.swing.JLabel lblPosicaoCalor;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblWorkerUrls;
    private javax.swing.JTextField txtWorkerUrls;
    private javax.swing.JPanel pnMalha;
    private javax.swing.JRadioButton rbParalelo;
    private javax.swing.JRadioButton rbSequencial;
    private javax.swing.JRadioButton rbDistribuido;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCoeficienteMaterial;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
