/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal.difusaocalor;

// import javax.swing.border.LineBorder; (não usado após remoção das bordas das células)
import java.awt.BorderLayout;
// import java.awt.Color; (não usado aqui)
import javax.swing.JOptionPane;

/**
 *
 * @author Kaneko
 */
public class FormPrincipal extends javax.swing.JFrame {

    private HeatGridPanel heatPanel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel lblStatus;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        // configura listeners adicionais que não são gerados pelo NetBeans
        setupListeners();
    }

    private void setupListeners() {
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateEnviarEnabled();
            }
        };
        txtAltura.getDocument().addDocumentListener(docListener);
        txtCoeficienteMaterial.getDocument().addDocumentListener(docListener);
        txtTempo.getDocument().addDocumentListener(docListener);

        // checkboxes already have action listeners generated -> reuse them to update
        // state
        // ensure initial state is correct
        updateEnviarEnabled();
    }

    private void updateEnviarEnabled() {
        boolean modeSelected = rbSequencial.isSelected() || rbParalelo.isSelected() || rbDistribuido.isSelected();
        boolean inputsFilled = !txtAltura.getText().trim().isEmpty()
                && !txtCoeficienteMaterial.getText().trim().isEmpty()
                && !txtTempo.getText().trim().isEmpty();
        boolean positionSelected = cbCima.isSelected() || cbBaixo.isSelected() || cbDireita.isSelected()
                || cbEsquerda.isSelected();
        btnEnviar.setEnabled(modeSelected && inputsFilled && positionSelected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDimensao = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        cbCima = new javax.swing.JCheckBox();
        cbBaixo = new javax.swing.JCheckBox();
        cbEsquerda = new javax.swing.JCheckBox();
        cbDireita = new javax.swing.JCheckBox();
        lblPosicaoCalor = new javax.swing.JLabel();
        lblCoeficienteMaterial = new javax.swing.JLabel();
        txtCoeficienteMaterial = new javax.swing.JTextField();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JToggleButton();
        pnMalha = new javax.swing.JPanel();
        rbParalelo = new javax.swing.JRadioButton();
        rbSequencial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDimensao.setText("Dimensão da Malha (X * Y)");

        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        cbCima.setText("Cima");
        cbCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCimaActionPerformed(evt);
            }
        });

        cbBaixo.setText("Baixo");
        cbBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaixoActionPerformed(evt);
            }
        });

        cbEsquerda.setText("Esquerda");
        cbEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsquerdaActionPerformed(evt);
            }
        });

        cbDireita.setText("Direita");
        cbDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDireitaActionPerformed(evt);
            }
        });

        lblPosicaoCalor.setText("Posição do calor");

        lblCoeficienteMaterial.setText("Coeficiente do Material ");

        txtCoeficienteMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoeficienteMaterialActionPerformed(evt);
            }
        });

        lblTempo.setText("Tempo (s)");

        txtTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        // inicialmente desabilitado até que um modo seja escolhido
        btnEnviar.setEnabled(false);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        // remover borda externa para que a malha comece na borda do painel
        pnMalha.setBorder(null);
        pnMalha.setToolTipText("");
        pnMalha.setName(""); // NOI18N
        pnMalha.setPreferredSize(new java.awt.Dimension(500, 500));
        // usamos BorderLayout como container para o painel customizado de desenho
        pnMalha.setLayout(new BorderLayout());

        // status (barra de progresso) será adicionado ao sul de pnMalha quando a malha
        // for criada

        // ordem desejada: Sequencial, Paralelo, Distribuído
        buttonGroup1.add(rbSequencial);
        rbSequencial.setText("Sequencial");
        rbSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSequencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbParalelo);
        rbParalelo.setText("Paralelo");
        rbParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParaleloActionPerformed(evt);
            }
        });

        // novo radio button para modo distribuído (ainda sem funcionalidade)
        rbDistribuido = new javax.swing.JRadioButton();
        buttonGroup1.add(rbDistribuido);
        rbDistribuido.setText("Distribuído");
        rbDistribuido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDistribuidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(txtAltura,
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lblDimensao,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(cbCima, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbDireita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbBaixo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbEsquerda,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbSequencial,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbParalelo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbDistribuido,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(83, 83, 83)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(lblCoeficienteMaterial,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txtCoeficienteMaterial)
                                                                .addComponent(txtTempo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblTempo))
                                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblPosicaoCalor))
                                .addGap(58, 58, 58)
                                .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblCoeficienteMaterial)
                                                        .addComponent(lblDimensao))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtCoeficienteMaterial,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblTempo)
                                                        .addComponent(rbSequencial))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rbParalelo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbDistribuido)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblPosicaoCalor)
                                                .addGap(21, 21, 21)
                                                .addComponent(cbCima)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbBaixo)
                                                        .addComponent(btnEnviar))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbDireita)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbEsquerda))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(btnLimpar)))))
                                .addContainerGap(16, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCimaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbCimaActionPerformed
        // estado do checkbox lido quando necessário pela simulação
        updateEnviarEnabled();
    }// GEN-LAST:event_cbCimaActionPerformed

    private void cbBaixoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbBaixoActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbBaixoActionPerformed

    private void cbEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbEsquerdaActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbEsquerdaActionPerformed

    private void cbDireitaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbDireitaActionPerformed
        // handler left intentionally simple; state read where needed
        updateEnviarEnabled();
    }// GEN-LAST:event_cbDireitaActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAlturaActionPerformed

    }// GEN-LAST:event_txtAlturaActionPerformed

    private void txtTempoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTempoActionPerformed
        try {
            Integer.parseInt(txtTempo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor inválido para tempo. Digite um inteiro.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_txtTempoActionPerformed

    private void txtCoeficienteMaterialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCoeficienteMaterialActionPerformed
        try {
            Double.parseDouble(txtCoeficienteMaterial.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor inválido para coeficiente. Digite um número.",
                    "Entrada inválida", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_txtCoeficienteMaterialActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }// GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
        gerarMalha();
        simularDifusao();
    }// GEN-LAST:event_btnEnviarActionPerformed

    private void rbParaleloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbParaleloActionPerformed
        // seleção alterada — atualiza estado do botão Enviar
        updateEnviarEnabled();
    }// GEN-LAST:event_rbParaleloActionPerformed

    private void rbSequencialActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbSequencialActionPerformed
        // seleção alterada — atualiza estado do botão Enviar
        updateEnviarEnabled();
    }// GEN-LAST:event_rbSequencialActionPerformed

    private void rbDistribuidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbDistribuidoActionPerformed
        // distribuído selecionado - funcionalidade não implementada ainda
        updateEnviarEnabled();
    }// GEN-LAST:event_rbDistribuidoActionPerformed

    private void limpar() {
        txtAltura.setText("");
        txtCoeficienteMaterial.setText("");
        txtTempo.setText("");
        pnMalha.removeAll();
        pnMalha.revalidate();
        pnMalha.repaint();
        cbCima.setSelected(false);
        cbBaixo.setSelected(false);
        cbDireita.setSelected(false);
        cbEsquerda.setSelected(false);
        buttonGroup1.clearSelection();
        // desabilita Enviar até nova seleção e atualiza estado
        updateEnviarEnabled();
    }

    private void gerarMalha() {
        int altura = 1;
        try {
            altura = Integer.parseInt(txtAltura.getText());
            if (altura <= 0)
                throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dimensão inválida. Digite um inteiro positivo.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        pnMalha.removeAll();

        // cria um painel customizado que desenha toda a malha em uma só superfície
        heatPanel = new HeatGridPanel(altura);
        pnMalha.add(heatPanel, BorderLayout.CENTER);

        // cria painel de status (barra de progresso + label) e adiciona ao sul da área
        // da malha
        progressBar = new javax.swing.JProgressBar(0, 100);
        progressBar.setValue(0);
        progressBar.setStringPainted(true);
        lblStatus = new javax.swing.JLabel("Pronto");
        javax.swing.JPanel statusPanel = new javax.swing.JPanel(new BorderLayout());
        statusPanel.add(progressBar, BorderLayout.CENTER);
        statusPanel.add(lblStatus, BorderLayout.EAST);
        pnMalha.add(statusPanel, BorderLayout.SOUTH);

        pnMalha.revalidate();
        pnMalha.repaint();
    }

    // ---------------- DIFUSÃO DE CALOR ----------------
    private void simularDifusao() {
        int n;
        double alpha;
        int tempoIteracoes;

        try {
            n = Integer.parseInt(txtAltura.getText());
            alpha = Double.parseDouble(txtCoeficienteMaterial.getText());
            tempoIteracoes = Integer.parseInt(txtTempo.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifique as entradas: dimensão, coeficiente e tempo devem ser números.", "Entrada inválida",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // cria o simulador (lógica separada) de acordo com a opção selecionada
        AbstractHeatSimulator simulator = null;
        if (rbSequencial.isSelected()) {
            simulator = new SequentialHeatSimulator(n, alpha);
        } else if (rbParalelo.isSelected()) {
            // modo paralelo ainda não implementado — avisa e usa sequencial como fallback
            JOptionPane.showMessageDialog(this, "Modo paralelo não implementado. Executando em modo sequencial.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            simulator = new SequentialHeatSimulator(n, alpha);
        } else if (rbDistribuido.isSelected()) {
            // modo distribuído ainda não implementado — avisa e usa sequencial como
            // fallback
            JOptionPane.showMessageDialog(this, "Modo distribuído não implementado. Executando em modo sequencial.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            simulator = new SequentialHeatSimulator(n, alpha);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um modo de execução (Sequencial/Paralelo/Distribuído).",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        simulator.setBoundaryFlags(cbCima.isSelected(), cbBaixo.isSelected(), cbEsquerda.isSelected(),
                cbDireita.isSelected());

        // local final usado dentro do Timer (lambda requer variável efetivamente final)
        final AbstractHeatSimulator sim = simulator;

        // se estivermos usando o painel customizado, atualizamos via heatPanel
        // java.awt.Component[] paineis = pnMalha.getComponents();

        // desabilita botões enquanto roda
        btnEnviar.setEnabled(false);
        btnLimpar.setEnabled(false);

        final int[] t = { 0 };
        int delayMs = 50; // controle visual da taxa de atualização

        final long startTime = System.nanoTime();
        final int totalSteps = tempoIteracoes;

        javax.swing.Timer timer = new javax.swing.Timer(delayMs, e -> {
            sim.step();

            double[][] T = sim.getTemperatureCopy();

            if (heatPanel != null) {
                heatPanel.setTemperature(T);
            } else {
                // fallback (não esperado)
                pnMalha.repaint();
            }

            t[0]++;

            // atualiza progress bar e status
            if (progressBar != null && lblStatus != null) {
                int step = t[0];
                int pct = Math.min(100, (int) ((step * 100L) / totalSteps));
                progressBar.setValue(pct);

                long now = System.nanoTime();
                long elapsedMs = (now - startTime) / 1_000_000L;
                long avgPerStep = step > 0 ? elapsedMs / step : 0;
                long remainingMs = avgPerStep * (totalSteps - step);

                lblStatus.setText(String.format("It: %d/%d — %s / %s", step, totalSteps, formatMs(elapsedMs),
                        formatMs(remainingMs)));
                this.setTitle(String.format("Difusão de Calor — %d%%", pct));
            }

            if (t[0] >= tempoIteracoes) {
                ((javax.swing.Timer) e.getSource()).stop();
                btnEnviar.setEnabled(true);
                btnLimpar.setEnabled(true);
                if (progressBar != null)
                    progressBar.setValue(100);
                if (lblStatus != null)
                    lblStatus.setText("Concluído — tempo: " + formatMs((System.nanoTime() - startTime) / 1_000_000L));
                this.setTitle("Difusão de Calor");
            }
        });

        timer.start();
    }

    // A conversão de temperatura para cor é feita em HeatGridPanel

    private static String formatMs(long ms) {
        long totalSec = ms / 1000;
        long min = totalSec / 60;
        long sec = totalSec % 60;
        return String.format("%02d:%02d", min, sec);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBaixo;
    private javax.swing.JCheckBox cbCima;
    private javax.swing.JCheckBox cbDireita;
    private javax.swing.JCheckBox cbEsquerda;
    private javax.swing.JLabel lblCoeficienteMaterial;
    private javax.swing.JLabel lblDimensao;
    private javax.swing.JLabel lblPosicaoCalor;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pnMalha;
    private javax.swing.JRadioButton rbParalelo;
    private javax.swing.JRadioButton rbSequencial;
    private javax.swing.JRadioButton rbDistribuido;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCoeficienteMaterial;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
