/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitorkaneko.difusaocalor;

import java.awt.BorderLayout;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author Kaneko
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDimensao = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        cbCima = new javax.swing.JCheckBox();
        cbBaixo = new javax.swing.JCheckBox();
        cbEsquerda = new javax.swing.JCheckBox();
        cbDireita = new javax.swing.JCheckBox();
        lblPosicaoCalor = new javax.swing.JLabel();
        lblCoeficienteMaterial = new javax.swing.JLabel();
        txtCoeficienteMaterial = new javax.swing.JTextField();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JToggleButton();
        pnMalha = new javax.swing.JPanel();
        rbParalelo = new javax.swing.JRadioButton();
        rbSequencial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDimensao.setText("Dimensão da Malha (X * Y)");

        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        cbCima.setText("Cima");
        cbCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCimaActionPerformed(evt);
            }
        });

        cbBaixo.setText("Baixo");
        cbBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaixoActionPerformed(evt);
            }
        });

        cbEsquerda.setText("Esquerda");
        cbEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsquerdaActionPerformed(evt);
            }
        });

        cbDireita.setText("Direita");
        cbDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDireitaActionPerformed(evt);
            }
        });

        lblPosicaoCalor.setText("Posição do calor");

        lblCoeficienteMaterial.setText("Coeficiente do Material ");

        txtCoeficienteMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoeficienteMaterialActionPerformed(evt);
            }
        });

        lblTempo.setText("Tempo (s)");

        txtTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        pnMalha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMalha.setToolTipText("");
        pnMalha.setName(""); // NOI18N
        pnMalha.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout pnMalhaLayout = new javax.swing.GroupLayout(pnMalha);
        pnMalha.setLayout(pnMalhaLayout);
        pnMalhaLayout.setHorizontalGroup(
            pnMalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        pnMalhaLayout.setVerticalGroup(
            pnMalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        buttonGroup1.add(rbParalelo);
        rbParalelo.setText("Parelelo");
        rbParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParaleloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSequencial);
        rbSequencial.setText("Sequêncial");
        rbSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSequencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAltura, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDimensao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbCima, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbParalelo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbSequencial, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCoeficienteMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCoeficienteMaterial)
                                .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTempo))
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPosicaoCalor))
                .addGap(58, 58, 58)
                .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoeficienteMaterial)
                            .addComponent(lblDimensao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoeficienteMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTempo)
                            .addComponent(rbParalelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbSequencial))
                        .addGap(18, 18, 18)
                        .addComponent(lblPosicaoCalor)
                        .addGap(21, 21, 21)
                        .addComponent(cbCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBaixo)
                            .addComponent(btnEnviar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDireita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEsquerda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnLimpar)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCimaActionPerformed
        boolean check = cbCima.isSelected();
    }//GEN-LAST:event_cbCimaActionPerformed

    private void cbBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBaixoActionPerformed
        boolean check = cbCima.isSelected();
    }//GEN-LAST:event_cbBaixoActionPerformed

    private void cbEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsquerdaActionPerformed
        boolean check = cbCima.isSelected();
    }//GEN-LAST:event_cbEsquerdaActionPerformed

    private void cbDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDireitaActionPerformed
        boolean check = cbCima.isSelected();
    }//GEN-LAST:event_cbDireitaActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void txtTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoActionPerformed
        int tempo = Integer.parseInt(txtTempo.getText());
        try{
            int tempoFinal = tempo;
        }catch(NumberFormatException e){
            System.out.println("Valor inválido, digite um valor númerico e inteiro");
        }
    }//GEN-LAST:event_txtTempoActionPerformed

    private void txtCoeficienteMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoeficienteMaterialActionPerformed
        double coef = Double.parseDouble(txtCoeficienteMaterial.getText());
        
        try{
            double coeficiente = coef;
        }catch(NumberFormatException e){
            System.out.println("Valor inválido, digite um valor numérico");
        }
    }//GEN-LAST:event_txtCoeficienteMaterialActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        gerarMalha();
        simularDifusao();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void rbParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParaleloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbParaleloActionPerformed

    private void rbSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSequencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSequencialActionPerformed
     
    private void limpar(){
        txtAltura.setText("");
        txtCoeficienteMaterial.setText("");
        txtTempo.setText("");
        pnMalha.removeAll();
        pnMalha.revalidate();
        pnMalha.repaint();
        cbCima.setSelected(false);
        cbBaixo.setSelected(false);
        cbDireita.setSelected(false);
        cbEsquerda.setSelected(false);
        buttonGroup1.clearSelection();
     }
    
    private void gerarMalha(){
        int i = 0;
        int j = 0;
        
        //Posicao base dos painéis
        int panelHeight = 500;
        int panelWidth = 500;
        int x = 0;
        int y = 0;
        
        //Recebe a altura e largura da malha em INT
        int altura = Integer.parseInt(txtAltura.getText());
        pnMalha.removeAll();
        //Gera a malha
        for(i = 0; i < altura; i++){

            for(j = 0; j < altura; j++){    
                javax.swing.JPanel painel = new javax.swing.JPanel();
                painel.setBorder(new LineBorder(Color.black));
                painel.setBounds(x, y, panelHeight/altura, panelWidth/altura);
                
                
                // Cria uma label dentro do painel
                //JLabel lbl = new JLabel("(" + i + "," + j + ")", SwingConstants.CENTER);
                //painel.add(lbl, BorderLayout.CENTER);
                
                
                pnMalha.add(painel);
                 x += (panelWidth/altura);
            }
            x = 0;
            y += (panelWidth/altura);
        }
        pnMalha.revalidate();
        pnMalha.repaint();
    }
    // ---------------- DIFUSÃO DE CALOR ----------------
    private void simularDifusao() {
        int n = Integer.parseInt(txtAltura.getText());
        double alpha = Double.parseDouble(txtCoeficienteMaterial.getText());
        int tempoIteracoes = Integer.parseInt(txtTempo.getText());

        double dx = 1.0, dy = 1.0;
        double dt = 0.1;

        double[][] T = new double[n][n];
        double[][] novoT = new double[n][n];

        // Condição inicial
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                T[i][j] = 20.0;
            }
        }

        // Define bordas com base nos checkboxes
        if (cbCima.isSelected()) for (int i = 0; i < n; i++) T[0][i] = 100.0;
        if (cbBaixo.isSelected()) for (int i = 0; i < n; i++) T[n - 1][i] = 100.0;
        if (cbEsquerda.isSelected()) for (int j = 0; j < n; j++) T[j][0] = 100.0;
        if (cbDireita.isSelected()) for (int j = 0; j < n; j++) T[j][n - 1] = 100.0;

        java.awt.Component[] paineis = pnMalha.getComponents();

        // 🔹 Contador de tempo (iterações)
        final int[] t = {0};

        // 🔹 Timer que atualiza as temperaturas progressivamente
        javax.swing.Timer timer = new javax.swing.Timer(1, e -> {
            // Cálculo da equação da difusão
            for (int i = 1; i < n - 1; i++) {
                for (int j = 1; j < n - 1; j++) {
                    double d2x = (T[i + 1][j] - 2 * T[i][j] + T[i - 1][j]) / (dx * dx);
                    double d2y = (T[i][j + 1] - 2 * T[i][j] + T[i][j - 1]) / (dy * dy);
                    novoT[i][j] = T[i][j] + alpha * dt * (d2x + d2y);
                }
            }

            // Mantém as bordas fixas
            if (cbCima.isSelected()) for (int i = 0; i < n; i++) novoT[0][i] = 100.0;
            if (cbBaixo.isSelected()) for (int i = 0; i < n; i++) novoT[n - 1][i] = 100.0;
            if (cbEsquerda.isSelected()) for (int j = 0; j < n; j++) novoT[j][0] = 100.0;
            if (cbDireita.isSelected()) for (int j = 0; j < n; j++) novoT[j][n - 1] = 100.0;

            // Atualiza matriz
            for (int i = 0; i < n; i++) {
                for (int j = 0; j < n; j++) {
                    T[i][j] = novoT[i][j];
                }
            }

            // Atualiza as cores
            for (int i = 0; i < n; i++) {
                for (int j = 0; j < n; j++) {
                    int index = i * n + j;
                    if (index < paineis.length) {
                        javax.swing.JPanel p = (javax.swing.JPanel) paineis[index];
                        p.setBackground(getColorFromTemperature(T[i][j]));
                    }
                }
            }

            pnMalha.repaint();

            // Incrementa o contador e para no tempo máximo
            t[0]++;
            if (t[0] >= tempoIteracoes) {
                ((javax.swing.Timer) e.getSource()).stop();
            }
        });

        timer.start();
    }


    // Converte uma temperatura (20–100 °C) para cor (azul → vermelho)
    private Color getColorFromTemperature(double temp) {
        // Limita o intervalo
        temp = Math.max(20, Math.min(100, temp));

        if (temp < 50) {
            // 20 → 50 : azul (0,0,255) → verde (0,255,0)
            double ratio = (temp - 20) / 30.0;
            int r = 0;
            int g = (int) (255 * ratio);
            int b = (int) (255 * (1 - ratio));
            return new Color(r, g, b);
        } else {
            // 50 → 100 : amarelo (255,255,0) → vermelho (255,0,0)
            double ratio = (temp - 50) / 50.0;
            int r = 255;
            int g = (int) (255 * (1 - ratio));
            int b = 0;
            return new Color(r, g, b);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBaixo;
    private javax.swing.JCheckBox cbCima;
    private javax.swing.JCheckBox cbDireita;
    private javax.swing.JCheckBox cbEsquerda;
    private javax.swing.JLabel lblCoeficienteMaterial;
    private javax.swing.JLabel lblDimensao;
    private javax.swing.JLabel lblPosicaoCalor;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pnMalha;
    private javax.swing.JRadioButton rbParalelo;
    private javax.swing.JRadioButton rbSequencial;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCoeficienteMaterial;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
